### ISSUE TITLE
View status of cross-organizational projects

### ISSUE THREAD

**Issue by DainialPadraig** [CodeForTucson/tech-exchange-for-civic-hackers#4]
As a user, I'd like to see status of cross-organizational projects (e.g., Python user group with Code for Tucson).

Size: 2

**Comment by pdtynan** [comment]
OK I recall that this was the one I agreed to do at out CfT meeting of 1-16-18.  As  a UxD person my plan is to both look at existing tools and talk with some potential users. Then I'll work up some kind of storyboard.

**Comment by pdtynan** [comment]
Rather than do a storyboard, I talked to people at our well-attended meeting of 2/6/18. I tried to find out what tools they had used to collaborate plus their major needs that were not fulfilled by the tools. People like Slack, Trello, gitHub and Visual Studio. They could not really think of major problems -- more of a personal choice or driven by the situation they were in.  Existing tools are so good not likely we can improve on them.  I think the solution is that when a project starts the participants have to agree on what to use.  There is little we can do to help except to promote the best ones or one that best fits the situation, like Slack for CfT projects. For this reason I would like to close this item.  If people disagree we can reopen it.

**Comment by DainialPadraig** [comment]
I'm not sure choosing a collaboration platform satisfies this use case, but maybe that's because it's not clearly defined. My understanding is that the user story was to have a tool for visualizing collaborations between groups - which could theoretically be done with Facebook or meetup, but not very elegantly. Perhaps we need to revisit this user story to make sure we understand it and that it really is something we think we need.

**Comment by pdtynan** [comment]
I agree that my conclusion is based on anecdotal evidence and personal opinion.  I am happy to open it again under a different definition or create a new one.  But I may not be the person to tackle it as I have not served as a contributor of code on a project. So for me I need other users to define an unserved need and to explain it in detail.  The thing I found daunting, also,  is that there are so many collaboration/status reporting tools out there. And it looks like they took a lot of resources to develop.  We need to define a strong missed opportunity to justify building our own or heavily customizing one that exists.  I don't have the technical background to size that.
